### PR TITLE
Fix permission error with Android M

### PR DESCRIPTION
**Pull request by Gnzlt**
Updated to fix SecurityException with Location permissions in Android M according to [Android 6.0 Changes guide](http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-hardware-id)

```
java.lang.SecurityException: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results
```

### CODE REVIEW

**Comment by davidgyoung** [comment]
@gnzlt, this permission is included in the manifest for the Android Beacon Library AAR file, so it gets merged into your app manifest automatically.  Thus, there should be no need to add it manually like in this PR.

Are you seeing otherwise?

**Comment by Gnzlt** [comment]
That's what it's supposed to happen, but it doesn't work. I think I've just realized it may occur because you're using the `<uses-permission-sdk-23>` tag instead of `<uses-permission-sdk23>` at the [Android Beacon Library Manifest](https://github.com/AltBeacon/android-beacon-library/blob/master/src/main/AndroidManifest.xml) according to the [Android Guide](http://developer.android.com/guide/topics/manifest/uses-permission-sdk23-element.html)

**Comment by davidgyoung** [comment]
Good thought, but I don't think that's it.  That [change](https://github.com/AltBeacon/android-beacon-library/commit/4ff78b05b4a5dc16b78ec069ab4ebf3c98af74f0) was only put in last week and has not been put in to the a binary release yet.  (You are using the binary release from JCenter/Maven specified in the reference app's build.gradle, yes? `compile 'org.altbeacon:android-beacon-library:2.6@aar'`)

**Comment by Gnzlt** [comment]
That's it!
So both tags works and the only "problem" was that it hasn't been released yet. Sorry for the nuisance, and thanks for creating a great library :wink:

**Comment by davidgyoung** [comment]
Just to make sure there is not a misunderstanding -- the binary library version 2.6 in JCenter/Maven *DOES* have a manifest entry to require ACCESS_COARSE_LOCATION... it just doesn't specify it to be sdk23 specific.  (The change that isn't in the binary release yet is to switch to a sdk23-specific permissions tag.)

So I'm still a little concerned that you had to add a permissions entry yourself.  You could not have to.  Make sense?

**Comment by Gnzlt** [comment]
Didn't realize you had this permission before "sdk23 tag change" commit.
I've just manually built the library in order to check it again without the JCenter/Maven release and the problem seems to be gone, but I don't see anything special on [latest commits](https://github.com/AltBeacon/android-beacon-library/compare/2.6.1...master)

**Comment by davidgyoung** [comment]
The change is in the binary release for 2.7.1

**Pull request closed without merging**
